### ISSUE TITLE
How to implement Vue.js in this boilerplate?

### ISSUE THREAD

**Issue by kravchenkoegor** [Miskamyasa/Vue-Express-Webpack-boilerplate#2]
Hello! I've just found your boilerplate, cloned the repo and installed dependencies. But now I can't understand how to implement Vue.js to this project. I want to develop front-end Vue and back-end Express simultaneously in one project with webpack. Please tell me how to do that

**Comment by Miskamyasa** [comment]
Vue allready installed, just import him in src/js/main.js and done.

**Comment by Miskamyasa** [comment]
made small changes for a simpler start

**Comment by kravchenkoegor** [comment]
Thank you very much, I really appreciate your fast answer) I see your point
